services:
  database:
    container_name: saas__mysql
    hostname: saas__database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saas-commerce
      MYSQL_USER: saascomerce
      MYSQL_PASSWORD: root
      TZ: America/Sao_Paulo
    ports:
      - '3306:3306'
    volumes:
      - ~/saas_mysql:/var/lib/mysql