services:
    database:
        container_name: saas_teste
        hostname: saas_teste_database
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: saas_teste
        ports:
            - '5432:5432'
        volumes:
            - ~/saas_teste:/var/lib/postgresql/data
